import { MovieGenre } from "../../models";

export const MOVIE_GENRES: MovieGenre[] = [
  { id: 1, name: "Ação", value: "action" },
  { id: 2, name: "Aventura", value: "adventure" },
  { id: 3, name: "Comédia", value: "comedy" },
  { id: 4, name: "Drama", value: "drama" },
  { id: 5, name: "Terror", value: "horror" },
  { id: 6, name: "Fantasia", value: "fantasy" },
  { id: 7, name: "Ficção Científica", value: "sci-fi" },
  { id: 8, name: "Romance", value: "romance" },
  { id: 9, name: "Mistério", value: "mystery" },
  { id: 10, name: "Animação", value: "animation" },
  { id: 11, name: "Documentário", value: "documentary" },
  { id: 12, name: "Musical", value: "musical" },
  { id: 13, name: "Biografia", value: "biography" },
  { id: 14, name: "Histórico", value: "historical" },
  { id: 15, name: "Guerra", value: "war" },
  { id: 16, name: "Policial", value: "crime" },
  { id: 17, name: "Suspense", value: "thriller" },
  { id: 18, name: "Western", value: "western" },
  { id: 19, name: "Esporte", value: "sports" },
  { id: 20, name: "Família", value: "family" },
  { id: 21, name: "Curta-Metragem", value: "short" },
  { id: 22, name: "Artes Marciais", value: "martial-arts" },
  { id: 23, name: "Noir", value: "noir" },
  { id: 24, name: "Faroeste Espacial", value: "space-western" },
  { id: 25, name: "Distopia", value: "dystopian" },
  { id: 26, name: "Cyberpunk", value: "cyberpunk" },
  { id: 27, name: "Steampunk", value: "steampunk" },
  { id: 28, name: "Fantasia Sombria", value: "dark-fantasy" },
  { id: 29, name: "Comédia Romântica", value: "rom-com" },
  { id: 30, name: "Surrealismo", value: "surrealism" },
];